// Initial structured seed data generator for Cloud Firestore collections
import { dbStore } from './db.js';

export const INITIAL_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Apollo Speciality Hospital',
    type: 'Multi-Speciality',
    address: 'Greams Lane, Off Greams Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0604,
    longitude: 80.2496,
    phone: '+91 44 2829 0200',
    emergency: true,
    open24x7: true,
    rating: 4.8,
    beds: { general: 42, icu: 14, emergency: 8, total: 250 },
    specialists: ['Cardiology', 'Neurology', 'Oncology', 'Orthopedics'],
    facilities: ['24/7 ICU', 'Trauma Center', 'Blood Bank', 'Helipad', 'MRI'],
    ambulanceAvailable: true,
    bloodBankAvailable: true,
  },
  {
    id: 'hosp-2',
    name: 'Fortis Malar Hospital',
    type: 'Super Speciality',
    address: 'No. 52, 1st Main Road, Gandhi Nagar, Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0067,
    longitude: 80.257,
    phone: '+91 44 4289 2222',
    emergency: true,
    open24x7: true,
    rating: 4.6,
    beds: { general: 28, icu: 9, emergency: 5, total: 180 },
    specialists: ['Cardiology', 'Pediatrics', 'Nephrology'],
    facilities: ['ICU', 'Emergency Care', 'Dialysis Unit', 'CT Scan'],
    ambulanceAvailable: true,
    bloodBankAvailable: true,
  },
  {
    id: 'hosp-3',
    name: 'MIOT International',
    type: 'Multi-Speciality',
    address: '4/112, Mount Poonamallee Road, Manapakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0223,
    longitude: 80.1764,
    phone: '+91 44 4200 2288',
    emergency: true,
    open24x7: true,
    rating: 4.7,
    beds: { general: 55, icu: 18, emergency: 12, total: 300 },
    specialists: ['Orthopedics', 'Trauma Care', 'Cardiology', 'Gastroenterology'],
    facilities: ['Trauma Center', 'Organ Transplant', 'ICU', 'Ambulance Service'],
    ambulanceAvailable: true,
    bloodBankAvailable: true,
  },
  {
    id: 'hosp-4',
    name: 'Manipal Hospital',
    type: 'Multi-Speciality',
    address: '98, HAL Old Airport Rd, Kodihalli',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9584,
    longitude: 77.6489,
    phone: '+91 80 2502 4444',
    emergency: true,
    open24x7: true,
    rating: 4.7,
    beds: { general: 38, icu: 12, emergency: 6, total: 220 },
    specialists: ['Cardiology', 'Oncology', 'Neurology', 'Pulmonology'],
    facilities: ['24/7 Emergency', 'ICU', 'Robotic Surgery', 'Blood Bank'],
    ambulanceAvailable: true,
    bloodBankAvailable: true,
  },
  {
    id: 'hosp-5',
    name: 'Ruby Hall Clinic',
    type: 'Multi-Speciality',
    address: '40, Sassoon Road',
    city: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5284,
    longitude: 73.8741,
    phone: '+91 20 6645 5100',
    emergency: true,
    open24x7: true,
    rating: 4.6,
    beds: { general: 30, icu: 10, emergency: 7, total: 200 },
    specialists: ['Cardiology', 'Neurology', 'Urology', 'Orthopedics'],
    facilities: ['Trauma Unit', 'ICU', 'Cath Lab', 'Ambulance'],
    ambulanceAvailable: true,
    bloodBankAvailable: true,
  },
];

export const INITIAL_DOCTORS = [
  {
    id: 'doc-1',
    name: 'Dr. Aarav Mehta',
    specialization: 'Cardiology',
    hospitalId: 'hosp-1',
    hospital: 'Apollo Speciality Hospital',
    city: 'Chennai',
    state: 'Tamil Nadu',
    qualification: 'MD, DM (Cardiology)',
    experience: 16,
    rating: 4.9,
    phone: '+91 98765 43210',
    available: true,
    consultationFee: 800,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300',
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '04:30 PM'],
  },
  {
    id: 'doc-2',
    name: 'Dr. Sunita Rao',
    specialization: 'Neurology',
    hospitalId: 'hosp-1',
    hospital: 'Apollo Speciality Hospital',
    city: 'Chennai',
    state: 'Tamil Nadu',
    qualification: 'MD, MCh (Neurosurgery)',
    experience: 14,
    rating: 4.8,
    phone: '+91 98765 43211',
    available: true,
    consultationFee: 900,
    image: 'https://images.unsplash.com/photo-1594824813566-78a9c2a048a6?w=300',
    availableSlots: ['09:30 AM', '11:00 AM', '03:00 PM'],
  },
  {
    id: 'doc-3',
    name: 'Dr. Rajesh Sharma',
    specialization: 'Orthopedics',
    hospitalId: 'hosp-3',
    hospital: 'MIOT International',
    city: 'Chennai',
    state: 'Tamil Nadu',
    qualification: 'MS (Orthopedics), FRCS',
    experience: 18,
    rating: 4.9,
    phone: '+91 98765 43212',
    available: true,
    consultationFee: 750,
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300',
    availableSlots: ['10:00 AM', '01:00 PM', '05:00 PM'],
  },
  {
    id: 'doc-4',
    name: 'Dr. Priya Deshmukh',
    specialization: 'Pediatrics',
    hospitalId: 'hosp-5',
    hospital: 'Ruby Hall Clinic',
    city: 'Pune',
    state: 'Maharashtra',
    qualification: 'MD (Pediatrics), DCH',
    experience: 11,
    rating: 4.7,
    phone: '+91 98765 43213',
    available: true,
    consultationFee: 650,
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300',
    availableSlots: ['11:00 AM', '02:30 PM', '04:00 PM'],
  },
];

export const INITIAL_AMBULANCES = [
  {
    id: 'amb-1',
    vehicleNumber: 'TN-01-AM-1008',
    hospitalId: 'hosp-1',
    hospital: 'Apollo Speciality Hospital',
    type: 'ALS (Advanced Life Support)',
    status: 'AVAILABLE',
    driverName: 'Ramesh Kumar',
    driverPhone: '+91 98400 12345',
    equipment: ['Ventilator', 'Defibrillator', 'Oxygen Cylinder', 'ECG Monitor'],
    rating: 4.9,
    distance: 1.8,
  },
  {
    id: 'amb-2',
    vehicleNumber: 'TN-01-AM-1009',
    hospitalId: 'hosp-2',
    hospital: 'Fortis Malar Hospital',
    type: 'BLS (Basic Life Support)',
    status: 'AVAILABLE',
    driverName: 'Suresh Babu',
    driverPhone: '+91 98400 67890',
    equipment: ['First Aid Kit', 'Stretcher', 'Oxygen Cylinder'],
    rating: 4.7,
    distance: 3.2,
  },
  {
    id: 'amb-3',
    vehicleNumber: 'MH-12-AM-4020',
    hospitalId: 'hosp-5',
    hospital: 'Ruby Hall Clinic',
    type: 'Cardiac Care Ambulance',
    status: 'AVAILABLE',
    driverName: 'Vikas Patil',
    driverPhone: '+91 98220 54321',
    equipment: ['Cardiac Monitor', 'Defibrillator', 'IV Pumps', 'O2 Supply'],
    rating: 4.8,
    distance: 2.4,
  },
];

export const INITIAL_BLOOD_BANKS = [
  {
    id: 'bb-1',
    name: 'Apollo Blood Bank',
    hospital: 'Apollo Speciality Hospital',
    city: 'Chennai',
    address: 'Greams Road, Chennai',
    phone: '+91 44 2829 3333',
    units: {
      'A+': 18, 'A-': 5,
      'B+': 22, 'B-': 6,
      'AB+': 10, 'AB-': 3,
      'O+': 25, 'O-': 2
    },
  },
  {
    id: 'bb-2',
    name: 'Rotary Blood Bank',
    hospital: 'Independent Regional Center',
    city: 'Chennai',
    address: 'Egmore, Chennai',
    phone: '+91 44 2819 1111',
    units: {
      'A+': 30, 'A-': 8,
      'B+': 35, 'B-': 10,
      'AB+': 15, 'AB-': 4,
      'O+': 40, 'O-': 6
    },
  },
];

export function initializeSeedData() {
  if (!dbStore.collections.hospitals || dbStore.collections.hospitals.length === 0) {
    dbStore.setCollection('hospitals', INITIAL_HOSPITALS);
  }
  if (!dbStore.collections.doctors || dbStore.collections.doctors.length === 0) {
    dbStore.setCollection('doctors', INITIAL_DOCTORS);
  }
  if (!dbStore.collections.ambulances || dbStore.collections.ambulances.length === 0) {
    dbStore.setCollection('ambulances', INITIAL_AMBULANCES);
  }
  if (!dbStore.collections.bloodBanks || dbStore.collections.bloodBanks.length === 0) {
    dbStore.setCollection('bloodBanks', INITIAL_BLOOD_BANKS);
  }
}

// Auto-seed on load
initializeSeedData();
